# fly.toml app configuration file generated for task-app-qt66aq on 2025-10-06T16:33:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'task-app-qt66aq'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
